//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ObjExp.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_QUICKFIND                   103
#define IDD_PROPERTIES                  107
#define IDR_MAINFRAME                   128
#define IDS_TITLE                       129
#define IDI_ALPC                        202
#define IDI_JOB                         203
#define IDI_COPY                        204
#define IDI_DELETE                      205
#define IDI_DESKTOP                     206
#define IDI_PASTE                       208
#define IDI_PROCESS                     209
#define IDI_CUT                         210
#define IDI_KEY                         211
#define IDI_PLAY                        212
#define IDI_OBJECTS                     213
#define IDI_PACKAGE                     214
#define IDI_REFRESH                     215
#define IDI_TYPES                       216
#define IDI_OBJECT                      217
#define IDI_THREAD                      218
#define IDI_EVENT                       219
#define IDI_MUTEX                       220
#define IDI_SEMAPHORE                   221
#define IDI_ATOM                        222
#define IDI_CALLBACK                    223
#define IDI_CAR                         224
#define IDI_DEVICE                      225
#define IDI_MEMORY                      226
#define IDI_FILE                        227
#define IDI_REGISTRY                    228
#define IDI_STRUCT                      229
#define IDI_WINSTATION                  230
#define IDI_DIRECTORY                   231
#define IDI_LINK                        232
#define IDI_TIMER                       233
#define IDI_SHIELD2                     234
#define IDI_FONT                        235
#define IDI_USER                        236
#define IDI_DEBUG                       237
#define IDI_PROFILE                     238
#define IDI_MESSAGE                     239
#define IDI_CHECK                       240
#define IDI_RADIO                       241
#define IDI_FOLDER_CLOSED               242
#define IDI_DATA                        243
#define IDI_PIN                         245
#define IDI_PARTITION                   246
#define IDI_COMMPORT                    247
#define IDI_EVENTVM                     248
#define IDI_MUTEXVM                     249
#define IDI_EVENT_KEY                   250
#define IDI_SILO                        251
#define IDI_DIRECTX                     252
#define IDI_COMPONENT                   253
#define IDI_ETW                         254
#define IDI_ETWREG                      255
#define IDI_PLUG                        256
#define IDR_CONTEXT                     257
#define IDD_OBJECTPROPS                 261
#define IDI_FIND                        264
#define IDI_SAVE                        265
#define IDI_PROPERTIES                  266
#define IDI_TARGET                      267
#define IDI_SEARCH                      269
#define IDI_LIST                        271
#define IDI_MAGNET                      272
#define IDI_PROCESS_KILL                273
#define IDI_PROCESS_ZOMBIE              274
#define IDI_MAGNET2                     275
#define IDD_PROCESSCHOOSER              276
#define IDD_HANDLES                     277
#define IDI_THREAD_ZOMBIE               278
#define IDI_INFO                        280
#define IDC_TYPE                        1000
#define IDC_NAME                        1001
#define IDC_HANDLES                     1002
#define IDC_REFS                        1003
#define IDC_PAGED                       1004
#define IDC_NPAGED                      1005
#define IDC_PERMANENT                   1006
#define IDC_EXCLUSIVE                   1007
#define IDC_TABS                        1007
#define IDC_SECURITY                    1008
#define IDC_ADDRESS                     1009
#define IDC_ADDRESSLABEL                1010
#define IDC_ALLHANDLES                  1011
#define IDC_LABEL                       1012
#define IDC_LABEL2                      1013
#define IDC_LABEL3                      1014
#define IDC_LABEL4                      1015
#define IDC_VALUE                       1017
#define IDC_VALUE2                      1018
#define IDC_VALUE3                      1019
#define IDC_VALUE4                      1020
#define IDC_FRAME                       1022
#define IDC_TEXT                        1023
#define IDC_LIST                        1024
#define IDC_REFRESH                     1025
#define IDC_SYSLINK                     1028
#define IDC_VERSION                     1029
#define IDC_COPYRIGHT                   1030
#define ID_WINDOW_CLOSE                 32772
#define ID_WINDOW_CLOSE_ALL             32773
#define ID_OPTIONS_ALWAYSONTOP          32775
#define ID_OPTIONS_FONT                 32776
#define ID_OBJECTS_ALLOBJECTS           32777
#define ID_OBJECTS_ALLHANDLES           32778
#define ID_OBJECTS_HANDLESINPROCESS     32779
#define ID_OPTIONS_MAINTAINLISTOFOBJECTSPERTYPE 32780
#define ID_OBJECTS_OBJECTMANAGERNAMESPACE 32781
#define ID_OBJECTS_OBJECTSOFTYPE        32782
#define ID_OBJECTS_PIPES                32783
#define ID_OBJECTS_MAILSLOTS            32784
#define ID_FILE_RUNASADMINISTRATOR      32785
#define ID_VIEW_REFRESH32786            32786
#define ID_VIEW_UPDATEINTERVAL          32787
#define ID_UPDATEINTERVAL_PAUSE         32788
#define ID_UPDATEINTERVAL_HALFSEC       32789
#define ID_UPDATEINTERVAL_1SECOND       32790
#define ID_UPDATEINTERVAL_2SECONDS      32791
#define ID_UPDATEINTERVAL_5SECONDS      32792
#define ID_UPDATEINTERVAL_10SECONDS     32793
#define ID_VIEW_PROPERTIES              32794
#define ID_OBJECTS_OBJECTTYPES          32795
#define ID_PAUSE                        32796
#define ID_RUN                          32797
#define ID_OPTIONS_THEME                32798
#define ID_OBJECTTREE_COPYFULLDIRECTORYNAME 32799
#define ID_OBJECTLIST_JUMPTOTARGET      32800
#define ID_OBJECTLIST_COPYFULLOBJECTPATH 32801
#define ID_PAUSERESUME                  32802
#define ID_TYPESLIST_ALLOBJECTS         32804
#define ID_TYPESLIST_ALLHANDLES         32805
#define ID_VIEW_FIND                    32806
#define ID_VIEW_QUICKFIND               32807
#define ID_OBJECTLIST_SHOWDIRECTORIESINLIST 32811
#define ID_OBJECTLIST_LISTMODE          32812
#define ID_SYSTEM_ZOMBIEPROCESSES       32813
#define ID_SYSTEM_PROCESSES             32814
#define ID_SYSTEM_THREADS               32815
#define ID_SYSTEM_SYSTEMINFORMATION     32816
#define ID_HANDLELIST_CLOSE             32817
#define ID_SYSTEM_ZOMBIETHREADS         32818
#define ID_HELP_ABOUTWINDOWS            32819
#define ID_OPTIONS_DARKMODE             32820

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        281
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
